DROP TABLE IF EXISTS liked;
DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS profile;

CREATE TABLE profile (
	profileId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	email VARCHAR(128) NOT NULL,
	phone VARCHAR(32),
	profileName VARCHAR(32) NOT NULL,
	UNIQUE(email),
	PRIMARY KEY(profileId)
);

CREATE TABLE post (
	postId INT UNSIGNED AUTO_INCREMENT NOT NULL,
	profileId INT UNSIGNED NOT NULL,
	postContent VARCHAR(20000) NOT NULL,
	postTime DATETIME NOT NULL,
	INDEX(profileId),
	FOREIGN KEY(profileId) REFERENCES profile(profileId),
	PRIMARY KEY(postId)
);

CREATE TABLE liked (
	profileId INT UNSIGNED NOT NULL,
	postId INT UNSIGNED NOT NULL,
	timeLiked DATETIME NOT NULL,
	INDEX(profileId),
	INDEX(postId),
	FOREIGN KEY(profileId) REFERENCES profile(profileId),
	FOREIGN KEY(postId) REFERENCES post(postId),
	PRIMARY KEY(profileId, postId)
);

